packages:
  - 'apps/*'
allowBuilds:
  '@firebase/util': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: true
  node: true
  prisma: set this to true or false
  protobufjs: true
